backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Skincare", "Wellness", "Beauty", "Lifestyle", "Self-Care", "Nutrition"]}
      - {label: "Reading Time (minutes)", name: "readingTime", widget: "number"}
      - {label: "Featured Post", name: "featured", widget: "boolean", default: false}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "picks"
    label: "Product Picks"
    folder: "src/content/picks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Skincare", "Makeup", "Hair Care", "Body Care", "Accessories", "Tools"]}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - {label: "Amazon Link", name: "amazon_link", widget: "string"}
      - {label: "Rating", name: "rating", widget: "number", value_type: "float", min: 0, max: 5, step: 0.5}
      - {label: "Featured Pick", name: "featured", widget: "boolean", default: false}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "src/content/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Featured Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"} 